project_id = "iibqglmxhaiecueqbudh"

[functions.send-meeting-reminders]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-deadline-reminders]
verify_jwt = false

[functions.send-comment-email]
verify_jwt = false

[functions.send-status-change-email]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.resend-invitation]
verify_jwt = false

[functions.send-process-sla-reminders]
verify_jwt = false

